### PR TITLE
Update events.yml to add DH2020 background tile

### PR DESCRIPTION
**Pull request by alexkraj**

### CODE REVIEW

**Review by tomnudd — CHANGES_REQUESTED** [review]
Hi!👋 Can you correct this to say “durhack_background” rather than “durjam_background”?

**Review by tomnudd — APPROVED** [review]
Thank you, looks good! 🙌

**Review by aaronosher — CHANGES_REQUESTED** [review]
Hey @alexkraj thanks for contributing, this is great!

I closed your previous PR #229 as the content of it and this PR should be consolidated.

Can you upload the tile banner to this branch (or enable maintainers to edit your branch, it should be a toggle on the PR). A direct link to it is here: https://raw.githubusercontent.com/Hackathons-UK/wiki/ee77f8d43361cc2732fb62da3124d3f3ed5a115f/docs/static/art/hackathon_tiles/durhack_background.png

Once you've done that I'll happily merge it.

**Review by aaronosher — APPROVED** [review]
turns out I could edit your branch, GitHub decided to be inconsistent...

**Pull request merged**
