### PR TITLE
Update Socials 

### PR DESCRIPTION
**Pull request by aaronosher**
We've moved away from the hackathon hackers eu brand. Thus, socials should reflect this.

I also added the Discord, however this required some overriding of the theme. The discord is only in the current version of font-awesome and the latest version of font-awesome is not used in mkdocs-material v4 because it would be a breaking change - squidfunk/mkdocs-material#756. I've overriden the font-awesome install, and the rendering of the social icons in the footer to support the latest version of font-awesome to add Discord. 

We should consider updating to v5 when exits preview.

### CODE REVIEW

**Comment by aaronosher** [comment]
@bahorn it looks like Netlify might need reconfiguring because of the org swithc.

**Comment by bahorn** [comment]
On it!

**Comment by bahorn** [comment]
Ok, just switched it. Doing it's first build now.

Might need another commit before it does the deploy preview.

**Comment by aaronosher** [comment]
> Might need another commit before it does the deploy preview.

`--allow-empty` ;)

**Comment by bahorn** [comment]
All seems good! Deploy preview looks perfect.

**Pull request merged**
