### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by tomMisson**

### CODE REVIEW

**Comment by ashie-princess** [comment]
Please don't merge your own PRs. It's bad practice, and this isn't your own private repo.

**Comment by robzwolf** [comment]
This PR hasn't been merged yet. Do you want it to be reviewed @tomMisson?

**Comment by tomMisson** [comment]
This was created by accident it wasn't merged and was intended for deletion however I forgot to. My bad, please don't review needs to be added to my existing PR about StudentHack Venue

**Comment by robzwolf** [comment]
Sure thing @tomMisson 👍

**Pull request closed without merging**
